# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 18:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authonline', '0017_auto_20161212_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('blog_id', models.AutoField(primary_key=True, serialize=False)),
                ('blog_title', models.CharField(default='', max_length=64)),
                ('blog_text', models.TextField()),
                ('blog_popular', models.IntegerField(default=0)),
                ('blog_post_date', models.DateTimeField(auto_now_add=True)),
                ('blog_modified_date', models.DateTimeField(auto_now=True)),
                ('blog_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_blog', to=settings.AUTH_USER_MODEL)),
                ('blog_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_blog', to='authonline.City')),
            ],
            options={
                'ordering': ['-blog_modified_date'],
            },
        ),
    ]
