# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_intro',
            field=models.CharField(default='', max_length=64),
        ),
    ]
