# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 22:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_blog_intro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-blog_popular']},
        ),
    ]
