# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authonline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='attraction_is_rec',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='city',
            name='city_is_rec',
            field=models.BooleanField(default=False),
        ),
    ]
