# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authonline', '0002_auto_20161113_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='city_name',
            field=models.CharField(default='', max_length=40),
        ),
    ]
