# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authonline', '0003_city_city_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='city_intro',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='city',
            name='city_province',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='city',
            name='city_rec_month',
            field=models.IntegerField(default=0),
        ),
    ]
