# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authonline', '0004_auto_20161114_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='city_img_src',
            field=models.CharField(default='', max_length=100),
        ),
    ]
