# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authonline', '0006_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='route_popular',
            field=models.IntegerField(default=0),
        ),
    ]
