# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 08:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authonline', '0007_route_route_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='route_create_time',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
