# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 09:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authonline', '0008_route_route_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='route_creator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='route_creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
