# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authonline', '0009_route_route_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='route_keywords',
            field=models.CharField(default='', max_length=40),
        ),
    ]
