# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 07:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authonline', '0011_route_route_modified_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(default='', max_length=32)),
                ('team_create_time', models.DateField(auto_now_add=True)),
                ('team_modified_time', models.DateField(auto_now=True)),
                ('team_closed', models.BooleanField(default=False)),
                ('team_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_creator', to=settings.AUTH_USER_MODEL)),
                ('team_member', models.ManyToManyField(related_name='team_member', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
