# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 08:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authonline', '0012_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_relation_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_relation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeamRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_relation_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_relation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='route',
            name='route_owner',
            field=models.ManyToManyField(related_name='route_owner', to='authonline.RouteRelation'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_member',
            field=models.ManyToManyField(related_name='team_member', to='authonline.TeamRelation'),
        ),
    ]
