# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-10 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authonline', '0013_auto_20161209_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='routerelation',
            name='route_relation_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamrelation',
            name='team_relation_id',
            field=models.IntegerField(default=0),
        ),
    ]
