# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 15:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authonline', '0014_auto_20161210_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_route',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='team_route', to='authonline.Route'),
            preserve_default=False,
        ),
    ]
