# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 15:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authonline', '0015_auto_20161211_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(default='', max_length=32)),
                ('team_create_time', models.DateField(auto_now_add=True)),
                ('team_modified_time', models.DateField(auto_now=True)),
                ('team_closed', models.BooleanField(default=False)),
                ('team_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeamRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_relation_id', models.IntegerField(default=0)),
                ('team_relation_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_relation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='team_member',
            field=models.ManyToManyField(related_name='team_member', to='authonline.TeamRelation'),
        ),
        migrations.AddField(
            model_name='team',
            name='team_route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_route', to='authonline.Route'),
        ),
    ]
