# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 15:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authonline', '0015_team_team_route'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='team_route',
        ),
    ]
