# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authonline', '0016_remove_team_team_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_route',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_route', to='authonline.Route'),
        ),
    ]
