# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 06:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authonline', '0016_auto_20161211_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='route_creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
