# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 15:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authonline', '0017_team_team_route'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='team_creator',
        ),
        migrations.RemoveField(
            model_name='team',
            name='team_member',
        ),
        migrations.RemoveField(
            model_name='team',
            name='team_route',
        ),
        migrations.RemoveField(
            model_name='teamrelation',
            name='team_relation_member',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='TeamRelation',
        ),
    ]
