# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('author', models.CharField(max_length=10, verbose_name='作者')),
                ('content', models.CharField(max_length=2000, verbose_name='正文')),
                ('post_date', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
            ],
            options={
                'ordering': ['-post_date'],
            },
        ),
    ]
